### PR TITLE
Add dark theme support

### PR DESCRIPTION
**Pull request by luclu7**
The old automatic "dark" theme was not awesome, so I tried adding a better support. I'm not a Sass expert, 
Old:
old theme

New:
"new" theme

image
image

### CODE REVIEW

**Comment by dhenry123** [comment]
Thank you very much for your interest.
Could you set the logo background to the same colour as the header background?
```css
.header .logo {
  margin: 4px;
  cursor: pointer;
  background-color: inherit;
  padding: 6px 6px 0 0;
  opacity: .7;
}
```

**Comment by luclu7** [comment]
The colors of the logo are a bit too dark to contrast correctly in my opinion
image

Inverse is waaaaay too awkward
image

This is `filter: brightness(0) invert(1);`, it's a bit sad without any color
image

Or maybe, just a "proper" rounded white background?
image

Which one would you prefer?

**Comment by dhenry123** [comment]
I've created a new branch: "logodarkmode".
Could you pull it and add the new file "client/public/assets/MytinyDC_logo-brand-full-darkmode.png" to your branch, then define the darkmode css accordingly...
Thank you so much

**Comment by luclu7** [comment]
This logo looks great !
image

**Comment by luclu7** [comment]
By the way, beware, the tag of the last release is 1.20 instead of 1.2.0

**Comment by dhenry123** [comment]
Thanks, I'll now avoid publishing a release while having breakfast. :)

**Pull request merged**
